databases:
  - name: poker-db
    plan: free
    databaseName: poker_platform

services:
  - type: web
    name: generic-poker
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: poker-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.12
